packages:
  - packages/core
  - packages/cli
  - packages/collector
  - apps/ecommerce
  - apps/blog
  - apps/dashboard
  - apps/desktop

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
